
* emacs-config
This configuration is for emacs >= 31

Third party packages:

guix: package/environment management. alternative is cli and setting exec-path-from-shell/environment

eat: graphical terminal emulation. alternative is built-in multi-term w/o visual commands

magit/forge: git/forge manipulation. alternative is built-in vc that lacks complex workflows like interactive rebase, forge pull requests or code review comments

org-roam: tag system for note database. alternative is org-node or self devised naming/search scheme with a datetree journal

osm: Map tile viewer. alternative is web browser viewing

gptel/mcp.el: interface with llms. alternative is llm package or cli

dape/geiser-guile/pyvenv/yaml: language specific modes

nov: epub reader. alternative is external program

reka: river wayland window manager for emacs to run applications inside emacs under external wayland desktops (needs pgtk feature).

** Clone
Branch names diverging and "." complicate fetching the correct heads.

#+NAME: clone
#+BEGIN_SRC sh :tangle no
git clone --single-branch --recurse-submodules --shallow-submodules --depth=1 ssh://git@codeberg.org/jamartin9/emacs-config.git
# get branch heads
git submodule foreach 'git checkout master'
#+END_SRC

** Tangle Install
Emacs untangles the script from the org file (using noweb to copy/eval code) while expanding INCLUDE directives.
Tangling is rerun when the org file is newer than the script (if present) and the html file.
Cleanup is done via the ~clean~ arguments to the ~make-el~ wrapper.
The wrapper is needed for org-roam, org-ids and html export tags.

#+NAME: tangle-install
#+BEGIN_SRC sh :tangle no
pwsh make-el.ps1 install
#+END_SRC

** Link
Installable org files tangle to a script of the same name for installation.
The script needs itself and emacs on the PATH or CWD.

#+NAME: link-README
#+BEGIN_SRC emacs-lisp :tangle README.sh :shebang "\":\"; emacs -Q --script README.sh -- $@ $args ; exit $? # -*- mode: emacs-lisp; lexical-binding: t; -*-"
(ignore-errors
      (make-symbolic-link (file-name-directory (or load-file-name buffer-file-name)) (concat (file-name-as-directory (if (getenv "XDG_CONFIG_HOME") (getenv "XDG_CONFIG_HOME") (concat (file-name-as-directory (getenv "HOME")) ".config"))) "emacs")))
#+END_SRC

** Run
The one line org-mode sesquicolon 'shebang' is a multipart shell/powershell wrapper.
Passed arguments to the elisp script are available by argv (ignoring “–” and “$@”).
To run with powershell use the same wrapper format with a .ps1 extension.
#+NAME: run-wrapper
#+BEGIN_SRC sh :tangle no
":"; emacs -Q --script README.sh -- $@ $args ; exit $? # -*- mode: emacs-lisp; lexical-binding: t; -*-
#+END_SRC

** Cherry Picking
Copy files by url with emacs
#+NAME: elisp-copy
#+BEGIN_SRC elisp :tangle no
(url-copy-file "https://codeberg.org/jamartin9/emacs-config/raw/branch/master/init.el" "init.el")
(url-copy-file "https://codeberg.org/jamartin9/emacs-config/raw/branch/master/early-init.el" "early-init.el")
(call-process "git" nil t nil "clone" "https://codeberg.org/jamartin9/emacs-config")
#+END_SRC

** Site
Clone the site
#+NAME: clone-gh-pages
#+BEGIN_SRC sh :tangle no
git worktree add --track -b pages ./pages origin/pages
#+END_SRC

Build the updated site
#+NAME: tangle-site
#+BEGIN_SRC sh :tangle no
pwsh make-el.ps1 site
#+END_SRC


** notes
- installs to ~${XDG_CONFIG_HOME}/emacs~
- early-init will use guix-home packages if emacs package directory exists inside it otherwise uses use-package to download
- Pure elisp instead of makefiles and shell scripts
  - sesquicolon 'shebang'
  - build system
    - runs any untangled elisp scripts
    - sets timestamps to 1 second after original file
    - exports custom elements for html/org-roam and expands INCLUDE directives
    - build site
      - git worktree
      - sitemap self untangles an org document
        - site search uses sqlite fts index and stores the db in opfs for reuse
          - uses Sync Access Handle
            - works without special headers
            - best perf for sqlite
            - pausing vfs for cross tab
      - copy js, css, png, sqlite db, etc by timestamp
        - migrated css from custom hand rolled to bulma then to pico for better defaults and less configuration
      - navbar contains index/sitemap links
        - INCLUDE in each page for css/navbar
    - wraps couple common commands
    - authinfo instead of pass
- org roam dialies are a date tree journal
- tangled files set own timestamps in scripts
- defaults copied from doom/spacemacs when dropped
- all keys bounds under C-c c
- prefer defaults when possible (ex fido instead of company)
- prefer eshell for tramp traversal
- gnus over newsticker as more backends and own the frame
  - gnus-cloud syncs authinfo.gpg over imap
- prefix named interactive commands over inline functions for M-x and binds
- added mouse clicking to command buffer
  - special case handling of Files:
- android support with termux build
- save files locally under .local/cache and .local/etc
- do not hardcode paths and use xdg
- tricks to speed up init
  - defer package loading with use-package
  - skip packages at startup
  - add memory for skipping gc
  - unbinding file-handler matching
  - native code
    - MAYBE change native-compile flags for elisp?
  - package-quickstart
  - autoload functions
  - dump saves a little time
  - after-init hooks
  - setq inhibits-*
  - disable frame features without loading
- gc with idle timer
- cua for copy/paste
- xterm/broadwayd/daemon support
- transparent background
- extra mouse support
- sound alert via ~org-timer-set-timer~
- packages in README for extras
  - functions under ~M-x jam/~ prefix
    - sudo-edit
    - auth-display
      - vendored totp implementation for authinfo password storage
    - draw
    - eshell
    - save-all (buffers)
    - mpv-play
    - screenshot
      - image-crop is a bind
      - ffmpeg for resize ~ffmpeg -i cropped.png -vf "scale=1280:720" scaled.png~
    - replace unicode
      - ZERO WIDTH NO-BREAK SPACE(BOM), ZERO WIDTH SPACE, RIGHT-TO-LEFT MARK, RIGHT-TO-LEFT OVERRIDE, LEFT-TO-RIGHT MARK, OBJECT REPLACEMENT CHARACTER
    - compile-init-bytecode
