
(defun spacemacs/custom-shell-link ()
  (interactive)
  (let (zsh-dir home-zshrc)
    (setq zsh-dir (concat (if (getenv "XDG_CONFIG_HOME")
                             (file-name-as-directory (getenv "XDG_CONFIG_HOME"))
                           (file-name-as-directory (concat (file-name-as-directory (getenv "HOME"))
                                                           ".config")))
                         "zsh"))
    (setq home-zshrc (concat (file-name-as-directory (getenv "HOME"))
                            ".zshrc"))
    (if (not (or (file-exists-p zsh-dir) (file-symlink-p zsh-dir)))
        (make-symbolic-link (concat dotspacemacs-directory
                                    (file-name-as-directory "layers")
                                    (file-name-as-directory "custom-shell")
                                    "zsh-config")
                            zsh-dir))
    (if (not (or (file-exists-p home-zshrc) (file-symlink-p home-zshrc)))
        (make-symbolic-link (concat dotspacemacs-directory
                                    (file-name-as-directory "layers")
                                    (file-name-as-directory "custom-shell")
                                    (file-name-as-directory "zsh-config")
                                    ".zshrc")
                            home-zshrc))))
